#!/bin/sh -e

# A simple script to change screen brightness.

# Path to brightness file, which holds value of current brightness
# This path may be different across systems, change it accordingly
# You will also need read/write access to this file
BRI_FILE='/sys/class/backlight/amdgpu_bl0/brightness'
CURR_BRI=$(cat "$BRI_FILE")

increase () {
    echo "$CURR_BRI" + 10 | bc > "$BRI_FILE"
}

decrease () {
    echo "$CURR_BRI" - 10 | bc > "$BRI_FILE"
}

help () {
    echo "Useage:\nUse 'd' or 'i' to decrease or increase screen brightness"
}

case $1 in
    i) increase  ;;
    d) decrease  ;;
    *) help ;;
esac
