#!/bin/sh -e
# A simple script to change screen brightness.

file='/sys/class/backlight/amdgpu_bl0/brightness'
read -r brightness < "$file"

case $1 in
    d) printf "%s\n" "$((brightness - 5))" > "$file" ;;
    i) printf "%s\n" "$((brightness + 5))" > "$file" ;;
    *) printf "%s\n" "usage: ${0##*/} d|i" ;;
esac
