#!/bin/sh

# draw a new terminal
# requires xrectsel

wf=8
hf=19
ib=2
ob=8

xrectsel | tr 'x+' ' ' | {
read w h x y
w=$(( ( w - (ib + ob)*2 ) / wf ))
h=$(( ( h - (ib + ob)*2 ) / hf ))
exec st -g ${w}x${h}+${x}+${y}
}
