#!/bin/sh -e

# A simple bookmarking script that uses dmenu

file_path="${XDG_CONFIG_HOME}/bmks"
filename=urls
bookmarks="${file_path}/${filename}"

usage() {
    printf "Usage: bmks a|d|l\n"
}

add() { 
	[ -z "${url}" ] && printf "Error: url must be provided\n" && exit 1
	printf "Description: "
	read -r description
	if [ -z "${description}" ]; then
		printf "%s\n" "${url}" >> "${bookmarks}"
	else
		printf "%s\n" "${description} - ${url}" >> "${bookmarks}"
	fi
}

list() {
	sort "${bookmarks}"
}

go_to() {
	[ ! -s "${bookmarks}" ] && printf "No bookmarks found. please add one" && exit 1
	[ -z "${BROWSER}" ] &&  printf 'BROWSER var not set\n' && exit 1
	SELECTION="$(sort "${bookmarks}" | dmenu -c -i -l 10 | awk '{print $(NF)}')"
	if [ -z "${SELECTION}" ]; then
		exit 1
	else
		exec "${BROWSER}" "${SELECTION}"
	fi
}

del() {
	sed "/$(sort "${bookmarks}" | dmenu -c -i -l 10)/d" "${bookmarks}" > _
	mv -f _ "${bookmarks}"
}

[ ! -d "${file_path}" ] && mkdir -p "${file_path}"
[ ! -f "${filename}" ] && touch "${file_path}/${filename}" 

case "$1" in
	h) usage ;;
	a) url=$2 add ;;
	l) list ;;
	d) del ;;
	*) go_to ;;
esac
