#!/bin/sh -e

# A simple bookmarking script that uses dmenu

[ -z "$BROWSER" ] &&  printf 'BROWSER var not set\n' && exit 1

file_path="$HOME/etc/bmks"
filename=urls
bookmarks="$file_path/$filename"

usage () {
    printf "bmks: A simple bookmarking script that uses dmenu

Usage:
bmks help
  show this message
bmks add <url>
  add a new bookmark
bmks del
  remove a bookmark
bmks ls
  list bookmarks

Configuration is done directly in script by editing the variables.
"

}
bmks_add () { 
	[ -z "$url" ] && printf "Error: url must be provided\n" && exit 1
	printf "Description: "
	read -r description
	[ -z "$description" ] && echo "$url" >> "$bookmarks"
	[ -n "$description" ] && echo "$description" - "$url" >> "$bookmarks"
}

bmks_ls () {
	sort "$bookmarks"
}

go_to () {
SELECTION="$(sort "${bookmarks}" | dmenu -c -i -l 10 | awk '{print $(NF)}')"
if [ -z "${SELECTION}" ]; then
	exit 1
else
	"${BROWSER}" "${SELECTION}"
fi
}

bmks_del () {
	case "$$" in
		*) sed "/$(sort "$bookmarks" | dmenu -c -i -l 10)/d" "$bookmarks" > _ && mv -f _ "$bookmarks" ;;
	esac
}

bmks_check () {
	if [ ! -s "${bookmarks}" ]; then
	printf "No bookmarks found. please add one"
	usage
	exit 1
	fi
}

[ ! -d "$file_path" ] && mkdir -p "$file_path"
[ ! -f "$filename" ] && touch "$file_path/$filename" 

case "$1" in
	help) usage ;;
	add) url=$2 bmks_add ;;
	ls) bmks_ls ;;
	del) bmks_del ;;
	*) go_to ;;
esac
