#!/bin/sh -e

# A tiny script for launching videos inside Videos dir with mpv
# No more need for a detached terminal taking up your screen space
# you can also delete the selected video with -d option

DIR="$HOME"/usr/vid

cd "$DIR"

case $1 in
  -d)
  rm -rf "$(find . -type f | awk -F "/" '{print $NF}' | dmenu -c -i -l 20 -p 'Delete:')"
  ;;
   *)
  mpv "$(find . -type f | awk -F "/" '{print $NF}' | dmenu -c -i -l 20 -p 'Play:')"
  ;;
esac
