#!/bin/sh -e

# tiny script to see files in Documents. mainly pdfs for me.
# opened with mupdf

# set DIR variable to whatever floats your boat
DIR="$HOME"/usr/doc

cd "$DIR"

case $1 in
  -d)
  rm -rf "$(find ./*.pdf -type f | awk -F "/" '{print $NF}' | dmenu -c -i -l 20 -p 'Delete:')"
  ;;
   *)
  exec mupdf "$(find ./*.pdf -type f |awk -F "/" '{print $NF}' | dmenu -c -i -l 20 -p 'View:')"
  ;;
esac
