#!/bin/sh -e

# Search the web from dmenu
# Does not handle URLs

# shellcheck disable=2153
browser="$BROWSER"

ENGINE='https://duckduckgo.com/?q='

# Spaces are not allowed, so substitute them to correct string
STRING=$(printf '' | dmenu -c -p 'Search' | sed 's/ /%20/g')

if [ -z "$STRING" ]; then
    exit 1
else
    "$browser" "$ENGINE$STRING"
fi
