#!/bin/sh
#
# z3bra - 2014 (c) wtfpl
# window focus wrapper that sets borders and can focus next/previous window

set -e

usage() {
    printf "usage: %s $(basename "$0") <next|prev|top|wid>\n"
    exit 1
}

case $1 in
    next) wid="$(lsw | grep -v $(pfw) | sed '1 p;d')" ;;
    prev) wid="$(lsw | grep -v $(pfw) | sed '$ p;d')" ;;
    top)  wid="$(lsw | sed '$ p;d')" ;;
    0x*)  wattr "$1" && wid="$1" ;;
    *)    usage ;;
esac

# exit if we can't find another window to focus
[ -z "${wid}" ] && exit 1

chwso -r "${wid}" # put it on top of the stack
wtf      "${wid}" # set focus on it
