#!/bin/sh -e
# simple screenshot

dir="$HOME/usr/scrots"
out="$dir/$(date +scrot-%Y%m%d-%H:%M).png"

[ -d "$(dir)" ] || mkdir -p "$(dir)"

ffmpeg \
	-hide_banner -loglevel error \
	-f x11grab -r 144 -draw_mouse 0 \
	-i "$DISPLAY" \
	-frames:v 1 \
	"$out"

echo "$out"
