#!/bin/sh -e

# Simple script to download videos
# Requires yt-dlp

# Set the download dir
DLDIR="$HOME"/usr/vid

nourl() {
    echo "Insert url"
    read -r url
    dl
}

ifurl() {
    # Check if an url has already been passed
   if [ -z "$url" ]; then 
       nourl 
   else
   dl
   fi
}

dl() {
       yt-dlp -F "$url"
       echo "Select quality. i.e. 248+251 or 22"
       read -r quality
       exec yt-dlp -P "$DLDIR" -f "$quality" "$url"
}

proxy() {
	ifurl
	PROXY="&local=true"
	url="$url$PROXY"
}

case $1 in
	-p) url=$2 proxy ;;
    *) url=$1 ifurl ;;
esac
